# Redirect default Netlify subdomain to primary domain

[[redirects]]
  from = "https://bandithijo.netlify.com/*"
  to = "https://bandithijo.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bandithijo.com/skripsi"
  to = "https://bandithijo.com/157/:splat"
  status = 301
  force = true

